Models/ViewModels/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EKContent.web.Models.Entities;

namespace EKContent.web.Models.ViewModels
{
    public class ReviewViewModel
    {
        public ContentWrapper ContentWrapper { get; set; }
        public Message Message { get; set; }
    }
}

Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using EKContent.web.Models.Database.Abstract;
using EKContent.web.Models.Services;
using EKContent.web.Models.ViewModels;

namespace EKContent.web.Controllers
{
    public class AuthController : Controller
    {
        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            ViewBag.Service = _service;
        }

        private PageService _service;

        public AuthController(IEKProvider dal)
        {
            _service = new PageService(dal);
        }

        public ActionResult Logon(HomeIndexViewModel homeIndexViewModel)
        {
            return RedirectToAction("Login", new {id = _service.GetHomePage().Id});
        }

        public ActionResult Login(int id, HomeIndexViewModel homeIndexViewModel)
        {
            var model = new LoginViewModel {};
            model.NavigationModel = homeIndexViewModel;
            return View(model);
        }

        public ActionResult Logout(int id)
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home", new { id = id });
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if (!Membership.ValidateUser(model.Username, model.Password))
            {
                ModelState.AddModelError("", "Username and/or Password are incorrect");
                return View(model);
            }
            else
            {
                FormsAuthentication.SetAuthCookie(model.Username, false);
                return RedirectToAction("Index", "Home", new { id = model.NavigationModel.Page.PageNavigation.Id });
            }
        }

        public ActionResult ChangePassword(int id, HomeIndexViewModel navModel)
        {
            var model = new PasswordChangeViewModel { };
            model.NavigationModel = navModel;
            return View(model);
        }

        [HttpPost]
        public ActionResult ChangePassword(PasswordChangeViewModel model)
        {
            if (!Membership.ValidateUser(Membership.GetUser().UserName, model.OldPassword))
                ModelState.AddModelError("OldPassword", "Incorrect Password");

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            _service.ChangePassword(model.OldPassword, model.NewPassword);
            TempData["message"] = "Password has been changed";
            return RedirectToAction("Index", "Home", new { id = model.NavigationModel.Page.PageNavigation.Id});
        }

    }
}

Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OAuth;
using DotNetOpenAuth.OAuth.ChannelElements;
using EKContent.web.Models.Database.Abstract;
using EKContent.web.Models.Entities;
using EKContent.web.Models.Services;
using EKContent.web.Models.ViewModels;
using EKContent.web.ThirdParty.Twitter;
using EKContent.web.Utilities;

namespace EKContent.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ColorController : BaseController
    {

        public ColorController(IEKProvider dal) : base(dal)
        {
        }




        public ActionResult Edit(int id)
        {
            var model = new ColorEditViewModel { Colors = _service.Dal.ColorProvider.Get() };
            model.NavigationModel = HomeIndexViewModelLoader.Create(id, _service);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ColorEditViewModel model)
        {

            _service.Dal.ColorProvider.Set(model.Colors);
            TempData["message"] = "Color settings have been set";
            return RedirectToAction("Edit", new {id = model.NavigationModel.Page.PageNavigation.Id});
        }

        [HttpPost]
        public ActionResult Add(ColorEditViewModel model)
        {
            ModelState.Clear();
            model.NavigationModel = HomeIndexViewModelLoader.Create(model.NavigationModel.Page.PageNavigation.Id, _service);
            model.Colors.Add(new EKContent.web.Models.Entities.Color {});
            return View("Edit", model);
        }
        [HttpPost]
        public ActionResult Remove(ColorEditViewModel model, int colorIdx)
        {
            ModelState.Clear();
            model.NavigationModel = HomeIndexViewModelLoader.Create(model.NavigationModel.Page.PageNavigation.Id, _service);
            model.Colors.RemoveAt(colorIdx);
            return View("Edit",  model);
        }

    }
}

Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using EKContent.web.Models.Database.Abstract;
using EKContent.web.Models.Services;
using EKContent.web.Models.ViewModels;
using System.IO;
using EKContent.web.Models.Entities;

namespace EKContent.web.Controllers
{
    [Authorize(Roles="Admin")]
    public class FileController : BaseController
    {


        public FileController(IEKProvider provider) : base(provider)
        {
        }

        public ActionResult List(int id, HomeIndexViewModel homeIndexViewModel)
        {
            var model = new FileListViewModel{Files = _service.Dal.FileProvider.Get()};
            model.NavigationModel = homeIndexViewModel;
            return View(model);
        }

        public ActionResult Create(int pageId, int? id)
        {
            var file = id.HasValue ? _service.Dal.FileProvider.Get().Single(i=>i.Id == id.Value) : new EKFile{};
            var model = new FileCreateViewModel { File = file};
            model.NavigationModel = HomeIndexViewModelLoader.Create(pageId, _service);
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(FileCreateViewModel model)
        {
            if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
            {
                var fileName = this.Request.Files[0].FileName;
                var extension = Path.GetExtension(fileName);
                model.File.FileName = String.Format("{0}{1}", Guid.NewGuid(), extension);

                //delete the old file
                if(!model.File.IsNew())
                {
                    var oldFile = _service.Dal.FileProvider.Get().Single(i => i.Id == model.File.Id).FileName;
                    var oldFilePath = this.Server.MapPath(String.Format("~/user_files/{0}", oldFile));
                    if (System.IO.File.Exists(oldFilePath))
                        System.IO.File.Delete(oldFilePath);

                }
                var saveTo = this.Server.MapPath(String.Format("~/user_files/{0}", model.File.NameWithExtension()));
                this.Request.Files[0].SaveAs(saveTo);
            }

            _service.Dal.FileProvider.Save(model.File);

            TempData["message"] = "File Saved";
            return RedirectToAction("List", new {id = model.NavigationModel.Page.PageNavigation.Id });
        }

        [HttpPost]
        public ActionResult Delete(int pageId, int id)
        {
            var file = _service.Dal.FileProvider.Get().Single(i => i.Id == id);
            _service.Dal.FileProvider.Delete(file.Id);
            var filePath = this.Server.MapPath(String.Format("~/user_files/{0}", file.FileName));

            if (System.IO.File.Exists(filePath))
                System.IO.File.Delete(filePath);

            TempData["message"] = "File Removed";
            return RedirectToAction("List", new { id = pageId });
        }



    }
}

Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EKContent.web.Models.Database.Abstract;
using EKContent.web.Models.ViewModels;

namespace EKContent.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MemberController : BaseAdminController
    {
        protected override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            ViewBag.Service = _service;
        }
        public MemberController(IEKProvider provider): base(provider)
        {

        }

        public ActionResult Index(HomeIndexViewModel model, int id)
        {
            var memberIndexViewModel = new MemberIndexViewModel
                                           {
                                               NavigationModel = model,
                                               Roles = _service.GetRoles()
                                           };
            return View(memberIndexViewModel);
        }
    }
}

Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OAuth;
using DotNetOpenAuth.OAuth.ChannelElements;
using EKContent.web.Models.Database.Abstract;
using EKContent.web.Models.Entities;
using EKContent.web.Models.Services;
using EKContent.web.Models.ViewModels;
using EKContent.web.ThirdParty.Twitter;
using EKContent.web.Utilities;

namespace EKContent.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SiteController : BaseController
    {

        public SiteController(IEKProvider dal) : base(dal)
        {

        }

        public ActionResult EditTwitterKeys(int id)
        {
            var model = new TwitterKeysEditViewModel { TwitterKeys = _service.GetTwitterKeys() };
            model.NavigationModel = HomeIndexViewModelLoader.Create(id, _service);
            return View(model);
        }


        public ActionResult StartAuth()
        {
            var consumer = _service.TwitterConsumer();
            var uri = new Uri(this.Request.Url.AbsoluteUri.Replace("Start", "End"));
            
            consumer.Channel.Send(consumer.PrepareRequestUserAuthorization(uri, null, null));
            return View();

        }

        public ActionResult EndAuth(int id)
        {
            var consumer = _service.TwitterConsumer();
            var authorizationTokenResponse = consumer.ProcessUserAuthorization();
            var keys = _service.Dal.TwitterKeysProvider.Get();
            keys.ApplicationAuthorizationKey = authorizationTokenResponse.AccessToken;
            keys.ApplicationAuthorizationSecret = new ShortTermTokenProvider().GetTokenSecret(authorizationTokenResponse.AccessToken);
            keys.Configured = true;
            _service.Dal.TwitterKeysProvider.Save(keys);
            TempData["message"] = "Twitter has been configured successfully.";
            return RedirectToAction("EditTwitterKeys", new { id = id });
           // Response.Write(authorizationTokenResponse.AccessToken);
           // if (authorizationTokenResponse == null)

             //   return RedirectToAction("Index", "Home");


        }
        public ActionResult ConfigureTwitter(int id)
        {
            TempData["message"] = "Twitter has been configured";
            return RedirectToAction("EditTwitterKeys", new { id = id });
        }

        [HttpPost]
        public ActionResult EditTwitterKeys(TwitterKeysEditViewModel model)
        {
            _service.SaveTwitterKeys(model.TwitterKeys);
            TempData["message"] = "Twitter keys have been set";
            return RedirectToAction("EditTwitterKeys",  new { id = model.NavigationModel.Page.PageNavigation.Id });
        }

        public ActionResult Edit(int id)
        {
            var model = new SiteEditViewModel { Site = _service.GetSite() };
            model.NavigationModel = HomeIndexViewModelLoader.Create(id, _service);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(SiteEditViewModel model)
        {
            if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0)
            {
                var fileName = this.Request.Files[0].FileName;
                var extension = Path.GetExtension(fileName); 
                //delete the old file
                if (!model.Site.IsNew())
                {
                    var oldImage = _service.GetSite().Logo;
                    var oldImagePath = this.Server.MapPath(String.Format("~/user_images/{0}", oldImage));
                    if (System.IO.File.Exists(oldImagePath))
                        System.IO.File.Delete(oldImagePath);
                }
                model.Site.Logo = String.Format("{0}{1}", Guid.NewGuid(), extension);
                //resize
                using(var bitMap =  ImageHelper.Instance().ResizeImage(Request.Files[0].InputStream, 20, 20))
                {
                    var saveTo = this.Server.MapPath(String.Format("~/user_images/{0}", model.Site.Logo));
                    bitMap.Save(saveTo);
                }

            };
            _service.SetSite(model.Site);
            TempData["message"] = "Site settings have been set";
            return RedirectToAction("Index", "Home", new {id = model.NavigationModel.Page.PageNavigation.Id});
        }

    }
}

Views/Shared/Body.cshtml
@model EKContent.web.Models.ViewModels.ContentWrapper

@{
    ViewBag.Title = "HTML";
}

@if (Model.Content.Body != null)
{
 <div style="margin-top:10px" class="well">
 @Html.Raw(ViewBag.Service.RenderImages(Model.Content.Body))
 </div>
}

Views/Shared/EditContentControls.cshtml
@model  EKContent.web.Models.ViewModels.ContentWrapper
@using EKContent.web.Models.ViewModels;
@{

}
@if (Roles.IsUserInRole("Admin") && Model.EditMode)
{
    <p>
    <div class="btn-group">
        <button data-href="@Url.Action("EditContent", new { Idx = Model.Idx, Mdx = Model.Mdx, pageId = Model.Page.Id }) " class="btn">
            <i class="icon-pencil"></i>Update Content</button>
         <button class="btn dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span></button>
        <ul class="dropdown-menu">
            <li>
        <a  data-toggle="modal" href="#delete-content-@Model.Idx">
            <i class="icon-trash"></i>Delete Content</a>
            </li>
        </ul>
    </div> 
    <div id="delete-content-@Model.Idx" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h3 id="myModalLabel">
                Warning!</h3>
        </div>
        <div class="modal-body">
            <p>
                Are you sure you want to delete this content?</p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">
                Cancel</button>
            <button class="btn btn-primary" data-action="@Url.Action("DeleteContent", new { Idx = Model.Idx, Mdx = Model.Mdx, pageId = Model.Page.Id })">
                Delete</button>
        </div>
    </div>
    </p> 
}

Views/Shared/File.cshtml
@model EKContent.web.Models.ViewModels.ContentWrapper

@{
    ViewBag.Title = "HTML";
}


@if (Model.Content.File != null)
{
    @*<div class="row" style="text-align:center">*@
    <p style="text-align:center;">
        <a href ="@Url.Action( "DownloadFile", "Home", new { id = Model.Content.FileId})" class="btn"><i class="icon-file"></i>Download</a>
    </p>

}

Views/Shared/ImageItem.cshtml
@model EKContent.web.Models.ViewModels.ContentWrapper

@{
    ViewBag.Title = "HTML";
}


@if (Model.Content.Image != null)
{
    @*<div class="row" style="text-align:center">*@
    <p style="text-align:center;">
    <img style="@(Model.Content.BorderImage? "border:solid 1px black;": String.Empty)padding:10px;border-radius:3px;" src="@Url.Content(String.Format("~/user_images/{0}", @Model.Content.Image.FileName))" />
    @if (Model.Content.ShowAddThis)
    {
        <a href="http://pinterest.com/pin/create/button/?url=@(Url.Encode(this.Request.Url.AbsoluteUri))&media=@Server.UrlEncode(String.Format("{0}{1}user_images/{2}", HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority), Url.Content("~/"), Model.Content.Image.FileName))&description=@Server.UrlEncode(Model.Content.Title)" data-pin-do="buttonPin" data-pin-config="above"><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
    }
    </p>
  @*  </div>*@
}

Views/Shared/Nav.cshtml
@model EKContent.web.Models.ViewModels.HomeIndexViewModel
@{
    ViewBag.Title = Model.Page.Title;
}
@Html.Partial("TopNavBar")
@if (!Model.Page.IsHomePage() && Model.PagePathList().Count > 2)
{
    <ul class="breadcrumb" @(Model.ShowBreadCrumb() ? "style=display:block" : String.Empty)>
        @for (var i = 0; i < Model.PagePathList().Count; i++)
        {
            if (Model.PagePathList()[i].IsHomePage())
            {
                continue;
            }
            if (Model.PagePathList().Count - 1 == i)
            {
            <li>@Model.PagePathList()[i].Title</li>
            }
            else
            {
            <li><a href="@Url.Action("Index", "Home", new { pageTitle = Model.PagePathList()[i].PagePath() }, null)">@Model.PagePathList()[i].Title</a>
                <span class="divider">/</span></li>            
            }
        }
    </ul>
}
@if (Model.ShowChildPages())
{
    if (Model.ChildPages().Count < 3)
    {
    <ul class="nav nav-pills nav-stacked">
        @foreach (var page in Model.ChildPages())
        {
            <li>@Html.ActionLink(page.Title, "Index", "Home", new { pageTitle = page.PagePath() }, null)</li>
        }
    </ul>
    }
    else
    {
        <select class="navigation span3">
        <option>-- also see --</option>
        @foreach (var page in Model.ChildPages())
        {
            <option value="@Url.Action("Index", "Home", new { pageTitle = page.PagePath() }, null)">@page.Title</option>
        } 
        </select>
    }
}
@if (Roles.IsUserInRole("Admin"))
{

    <div class="control-group">
        @Html.ActionLink(String.Format("Switch to {0}", Model.UserMode ? " Edit Mode" : "User Mode"), "Index", "Home", new { id = Model.Page.Id, userMode = !Model.UserMode }, null)
    </div>
    
    if (Model.EditMode())
    {
    <div class="btn-group" style="margin-bottom: 5px">
        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-wrench">
        </i>Admin Actions <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li>
                <a href="@Url.Action("EditContent", "Home", new { Idx = -1, Mdx = 0, pageId = Model.Page.Id })">
                    <i class="icon-plus"></i>Create Content</a>
            </li>
            <li>
                <a href="@Url.Action("EditPage", "Home", new { pageId = Model.Page.Id })">
                    <i class="icon-wrench"></i>Edit Page</a>
            </li>
            <li><a href="@Url.Action("EditPage", "Home",  new { parentId = Model.Page.Id })">
                <i class="icon-plus"></i>Add Page</a>
            </li>
            <li class="divider"></li>
            @if (Model.CanDelete())
            {
                <li><a data-toggle="modal" href="#delete-page"><i class="icon-trash">
                </i>Delete Page</a></li>
            }
            <li><a  href = "@Url.Action("List", "Image", new { id = Model.Page.Id })">
                <i class="icon-picture"></i>Image Gallery</a></li>
            <li><a  href = "@Url.Action("List", "File", new { id = Model.Page.Id })">
                <i class="icon-file"></i>File Gallery</a></li>
            <li><a  href = "@Url.Action("Edit", "Site", new { id = Model.Page.Id })">
                <i class="icon-globe"></i>Site Settings</a></li>
            <li><a  href = "@Url.Action("EditTwitterKeys", "Site", new { id = Model.Page.Id })">
                <i class="icon-asterisk"></i>Twitter Settings</a></li>
            <li><a href = "@Url.Action("Index", "Member", new { id = Model.Page.Id })">
                <i class="icon-user"></i>Manage Users</a></li>
            <li><a href = "@Url.Action("Edit", "StyleSettings", new { id = Model.Page.Id })">
                <i class="icon-text-width"></i>Style Settings</a></li>
            <li><a href = "@Url.Action("Edit", "Color", new { id = Model.Page.Id })">
                <i class="icon-tint"></i>Color Settings</a></li>
        </ul>
    </div>
    
    <div id="delete-page" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h3 id="myModalLabel">
                Warning!</h3>
        </div>
        <div class="modal-body">
            <p>
                Are you sure you want to delete this page?</p>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">
                Cancel</button>
            <button class="btn btn-primary" data-action="@Url.Action("DeletePage", new { id = Model.Page.Id })">
                Delete</button>
        </div>
    </div>
    }
}

Views/Shared/ReviewForm.cshtml
@model EKContent.web.Models.ViewModels.ReviewViewModel
@{
    ViewBag.Title = "HTML";
}
 
    <p>
    <a class="btn btn-primary btn-large" data-toggle="modal" href="#modal-review">Add your own review!</a>
    </p>
            <div id="modal-review" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    @using (Html.BeginForm("SendMessage", "Home", new { id = Model.ContentWrapper.Page.Id }, FormMethod.Post))
    {
    <input type="hidden" name="review" value="true" />
 <div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel">Add Your Review!!</h3>
</div>
<div class="modal-body">
    @Html.Partial("ReviewFormControls", Model.Message)
    </div>
<div class="modal-footer">
<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
<button id="contact-submit" type="submit" class="btn btn-primary input-medium">Send Review</button>
</div>
  
    }  </div>

Views/Shared/ReviewFormControls.cshtml
@model EKContent.web.Models.Entities.Message
@{
    ViewBag.Title = "HTML";
}
 
    @Html.HiddenFor(m=>m.IsReview)
    @Html.TextBoxFor(m=>m.Name, new{@class=String.Format("span{0}", Model.IsReview?"3" : "6"), placeholder="Your Name"})
    @Html.ValidationMessageFor(m => m.Name)
    @Html.TextBoxFor(m => m.Email, new { @class = String.Format("span{0}", Model.IsReview ? "3" : "6"), placeholder = "Your Email" })
    @Html.ValidationMessageFor(m => m.Email)
    <div class="controls">
    <textarea id="message" name="Body" class="span@(Model.IsReview?"3" : "6")" placeholder="@(Model.IsReview?"Your Review" : "Your Message")" rows="5"></textarea>
    </div>

Views/Shared/SaveCancelButtons.cshtml
@{
    ViewBag.Title = "SaveCancelButtons";
}


    <button type="submit" value="save" class="btn btn-primary btn-large">Save</button>
    <button class="btn btn-large" data-href=@Url.Action("Index", "Home", new { id = Model.NavigationModel.Page.Id })>Cancel</button>

Views/Shared/TopNavBar.cshtml
@model EKContent.web.Models.ViewModels.HomeIndexViewModel
@{
    ViewBag.Title = Model.Page.Title;
}
<style>
@Model.Site.IconStyleString();
</style>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </a>
            
            <a class="brand" href="@Url.Action("Index", "Home", new { pageTitle = Model.Pages.Single(p=>p.IsHomePage()).PagePath(), id = (int?)null })"><i class="@Model.Site.IconLogo()"></i>@Model.Site.Title</a>
            
            <div class="nav-collapse collapse">
                <ul class="nav">
                    @foreach (var page in Model.TopLevelPages())
                    {
                         <li @(Model.Page.Id == page.Id ? "class=active" : String.Empty)>@Html.ActionLink(page.Title, "Index", "Home", new { pageTitle = page.PagePath() }, null)</li>
                    }
                    <li class="nav-header">User Actions:</li>
<li><a  href = "@Url.Action(User.Identity.IsAuthenticated ? "Logout" : "Login", "Auth", new { id = Model.Page.Id })"><span class="badge badge-info">@( User.Identity.IsAuthenticated ? "Logout" : "Login")</span></a></li>
        @if (User.Identity.IsAuthenticated)
        {
            <li><a  href = "@Url.Action("ChangePassword", "Auth", new { id = Model.Page.Id })"><span class="badge badge-info">Change
                Password</span></a></li>
            <li><a  href = "@Url.Action("Help", "Home", new { id = Model.Page.Id })"><span class="badge badge-important">
                Help</span></a></li>            
        }
                </ul>
            </div>
        </div>
    </div>
</div>

@if (Model.PagePathList().Count < 3)
{
<select class="alternative-navigation span2 navigation">
            <option value="@Url.Action("Index", "Home", new { pageTitle = Model.Pages.Single(p => p.IsHomePage()).PagePath(), id = (int?)null })">@Model.Site.Title</option>
            
                    @foreach (var page in Model.TopLevelPages())
                    {
                         <option value="@Url.Action("Index", "Home", new { pageTitle = page.PagePath() }, null)" @(Model.Page.Id == page.Id ? "selected=selected" : String.Empty)>@page.Title</option>
                    }
</select>
}

Views/Shared/TwitterFeed.cshtml
@model EKContent.web.Models.ViewModels.TwitterTimelineViewModel

@{
    ViewBag.Title = "Index";
    Layout = null;
}
@if (Model.ShowFeed)
{ 
<h4><a href=@Model.TwitterLink>Check us out on Twitter</a></h4>

       
       
        <table class="table table-striped">
            @for (int x = 0; x < Model.Tweets.Count(); x++)
            {

                Newtonsoft.Json.Linq.JObject tweet = Newtonsoft.Json.Linq.JObject.Parse(Model.Tweets[x].ToString());
                const string format = "ddd MMM dd HH:mm:ss zzzz yyyy";
                
                <tr>
                <td>
                    <img style="width:48px;height:48px;max-width:48px;" src="@tweet["user"]["profile_image_url"]" />
                 </td> 
                 <td>
                 <blockquote style="font-size:smaller">
                @tweet["text"].ToString()
                <small>@tweet["user"]["name"] <text>@@</text>@(tweet["user"]["screen_name"]) on @DateTime.ParseExact(tweet["created_at"].ToString(), format, System.Globalization.CultureInfo.InvariantCulture)from @tweet["user"]["location"].ToString()</small>
                </blockquote>  
                <br />

                </td>
                </tr>
            }
        </table>
}